import Form from "./Form.vue";
import Label from "./Label.vue";
import Input from "./Input.vue";
import TextArea from "./TextArea.vue";
import Button from "./Button.vue";
import Select from "./Select.vue";
import Radio from "./Radio.vue";
import FieldGroup from "./FieldGroup.vue";
import CheckBox from './CheckBox.vue';
export { Form, Label, Input, TextArea, Button, Select, FieldGroup, Radio, CheckBox };
